var questions = [
  {
      "question": "What's something you keep in your car just in case?",
      "answerOne": "Money",
      "answerTwo": "Food",
      "answerThree": "First Aid Kit",
      "answerFour": "Spare Tire",
      "answerFive": "Map",
      "answerSix": "Jumper Cables",
      "answerSeven": "Clothes",
      "answerEight": "Gas Can",
      "answerOnePts": 19,
      "answerTwoPts": 18,
      "answerThreePts": 18,
      "answerFourPts": 15,
      "answerFivePts": 7,
      "answerSixPts": 7,
      "answerSevenPts": 5,
      "answerEightPts": 2,
      "numberOfQuestions": 8
  },
  {
      "question": "When you enter a bathroom, what color do you really hope not to see in the toilet bowl?",
      "answerOne": "Brown",
      "answerTwo": "Yellow",
      "answerThree": "Red",
      "answerFour": "Green",
      "answerFive": "Black",
      "answerSix": "Pink",
      "answerOnePts": 61,
      "answerTwoPts": 11,
      "answerThreePts": 10,
      "answerFourPts": 10,
      "answerFivePts": 2,
      "answerSixPts": 1,
      "numberOfQuestions": 6
  },
  {
      "question": "Name something in a person's closet that only comes out on special occasions.",
      "answerOne": "Suit",
      "answerTwo": "Dress",
      "answerThree": "Jewelry",
      "answerFour": "Heels",
      "answerFive": "Gun",
      "answerOnePts": 35,
      "answerTwoPts": 26,
      "answerThreePts": 10,
      "answerFourPts": 6,
      "answerFivePts": 4,
      "numberOfQuestions": 5
  },
  {
      "question": "Name something you'd find in a breakfast buffet.",
      "answerOne": "Eggs",
      "answerTwo": "Bacon",
      "answerThree": "Sausage",
      "answerFour": "Potatoes",
      "answerFive": "Juice",
      "answerSix": "Coffee",
      "answerSeven": "Melon",
      "answerEight": "Cereal",
      "answerOnePts": 25,
      "answerTwoPts": 24,
      "answerThreePts": 19,
      "answerFourPts": 12,
      "answerFivePts": 7,
      "answerSixPts": 6,
      "answerSevenPts": 2,
      "answerEightPts": 2,
      "numberOfQuestions": 8
  },
  {
      "question": "Name a professional sport where the players make a lot of money.",
      "answerOne": "Football",
      "answerTwo": "Baseball",
      "answerThree": "Basketball",
      "answerFour": "Soccer",
      "answerFive": "Tennis",
      "answerSix": "Darts",
      "answerOnePts": 29,
      "answerTwoPts": 27,
      "answerThreePts": 24,
      "answerFourPts": 7,
      "answerFivePts": 7,
      "answerSixPts": 2,
      "numberOfQuestions": 6
  },
  {
      "question": "Name one of Marvel's Avengers.",
      "answerOne": "Captain America",
      "answerTwo": "Iron Man",
      "answerThree": "Black Panther",
      "answerFour": "The Hulk",
      "answerFive": "Thor",
      "answerSix": "Black Widow",
      "answerSeven": "Spiderman",
      "answerEight": "Hawkeye",
      "answerOnePts": 22,
      "answerTwoPts": 22,
      "answerThreePts": 20,
      "answerFourPts": 15,
      "answerFivePts": 15,
      "answerSixPts": 9,
      "answerSevenPts": 3,
      "answerEightPts": 3,
      "numberOfQuestions": 8
  },
  {
      "question": "Name a state that has a lot of sports teams.",
      "answerOne": "New York",
      "answerTwo": "California",
      "answerThree": "Florida",
      "answerFour": "Texas",
      "answerFive": "Pennsylvania",
      "answerSix": "Illinois",
      "answerOnePts": 33,
      "answerTwoPts": 30,
      "answerThreePts": 18,
      "answerFourPts": 13,
      "answerFivePts": 3,
      "answerSixPts": 2,
      "numberOfQuestions": 6
  },
  {
      "question": "Name a common candy bar component.",
      "answerOne": "Chocolate",
      "answerTwo": "Peanuts",
      "answerThree": "Caramel",
      "answerFour": "Almonds",
      "answerFive": "Nougat",
      "answerSix": "Coconut",
      "answerOnePts": 36,
      "answerTwoPts": 22,
      "answerThreePts": 15,
      "answerFourPts": 12,
      "answerFivePts": 10,
      "answerSixPts": 6,
      "numberOfQuestions": 6
  },
  {
      "question": "Name something you would buy after getting engaged.",
      "answerOne": "Dress",
      "answerTwo": "Ring",
      "answerThree": "Champagne",
      "answerFour": "Dinner",
      "answerOnePts": 44,
      "answerTwoPts": 31,
      "answerThreePts": 11,
      "answerFourPts": 6,
      "numberOfQuestions": 4
  },
  {
      "question": "Name a decision that people don't make lightly.",
      "answerOne": "Marriage",
      "answerTwo": "Divorce",
      "answerThree": "Buying A House",
      "answerFour": "Having Kids",
      "answerFive": "Accepting A Job",
      "answerOnePts": 61,
      "answerTwoPts": 12,
      "answerThreePts": 11,
      "answerFourPts": 8,
      "answerFivePts": 3,
      "numberOfQuestions": 5
  },
  {
      "question": "Name a character who's known for almost ruining Christmas.",
      "answerOne": "Grinch",
      "answerTwo": "Scrooge",
      "answerThree": "Charlie Brown",
      "answerOnePts": 67,
      "answerTwoPts": 28,
      "answerThreePts": 4,
      "numberOfQuestions": 3
  },
  {
      "question": "If you lived on Sesame Street, which character would get on your nerves?",
      "answerOne": "Big Bird",
      "answerTwo": "Elmo",
      "answerThree": "Oscar",
      "answerFour": "Cookie Monster",
      "answerFive": "Ernie",
      "answerSix": "Grover",
      "answerOnePts": 41,
      "answerTwoPts": 19,
      "answerThreePts": 15,
      "answerFourPts": 14,
      "answerFivePts": 4,
      "answerSixPts": 3,
      "numberOfQuestions": 6
  },
  {
      "question": "On a scale from 1-10, how good are you at keeping a secret?",
      "answerOne": "10",
      "answerTwo": "5",
      "answerThree": "8",
      "answerFour": "9",
      "answerOnePts": 31,
      "answerTwoPts": 28,
      "answerThreePts": 21,
      "answerFourPts": 18,
      "numberOfQuestions": 4
  },
  {
      "question": "Name a fruit you might eat in the morning.",
      "answerOne": "Banana",
      "answerTwo": "Grapefruit",
      "answerThree": "Strawberry",
      "answerFour": "Apple",
      "answerFive": "Orange",
      "answerSix": "Melon",
      "answerSeven": "Peach",
      "answerOnePts": 25,
      "answerTwoPts": 22,
      "answerThreePts": 19,
      "answerFourPts": 15,
      "answerFivePts": 12,
      "answerSixPts": 3,
      "answerSevenPts": 2,
      "numberOfQuestions": 7
  },
  {
      "question": "Name something drivers often do if they spot a police car up ahead.",
      "answerOne": "Slow Down",
      "answerTwo": "Move Over",
      "answerThree": "Put Seatbelt On",
      "answerOnePts": 71,
      "answerTwoPts": 12,
      "answerThreePts": 4,
      "numberOfQuestions": 3
  },
  {
      "question": "What traffic signs describe your life style?",
      "answerOne": "Stop",
      "answerTwo": "Green Light",
      "answerThree": "Yield",
      "answerFour": "Dead End",
      "answerFive": "Do Not Enter",
      "answerSix": "Curves Ahead",
      "answerOnePts": 44,
      "answerTwoPts": 17,
      "answerThreePts": 13,
      "answerFourPts": 8,
      "answerFivePts": 7,
      "answerSixPts": 6,
      "numberOfQuestions": 6
  },
  {
      "question": "Name a hobby whose participants are also called Geeks.",
      "answerOne": "Chess",
      "answerTwo": "Computer",
      "answerThree": "Video Games",
      "answerFour": "Math",
      "answerFive": "Band",
      "answerOnePts": 42,
      "answerTwoPts": 35,
      "answerThreePts": 9,
      "answerFourPts": 7,
      "answerFivePts": 5,
      "numberOfQuestions": 5
  },
  {
      "question": "Name a type of insurance.",
      "answerOne": "Car",
      "answerTwo": "Health",
      "answerThree": "Life",
      "answerFour": "Home",
      "answerFive": "Renter's",
      "answerSix": "Flood",
      "answerSeven": "Travel",
      "answerEight": "Blackjack",
      "answerOnePts": 28,
      "answerTwoPts": 22,
      "answerThreePts": 15,
      "answerFourPts": 10,
      "answerFivePts": 8,
      "answerSixPts": 6,
      "answerSevenPts": 4,
      "answerEightPts": 2,
      "numberOfQuestions": 8
  },
  {
      "question": "Name something people forget to do when in a hurry to leave the house.",
      "answerOne": "Lock The Door",
      "answerTwo": "Turn Off The Lights",
      "answerThree": "Grab Keys",
      "answerFour": "Brush Teeth",
      "answerOnePts": 43,
      "answerTwoPts": 30,
      "answerThreePts": 13,
      "answerFourPts": 12,
      "numberOfQuestions": 4
  },
  {
      "question": "At your job, out of the 60 minutes in each hour, how many do you spend doing actual work?",
      "answerOne": "45 minutes",
      "answerTwo": "30 minutes",
      "answerThree": "50 minutes",
      "answerFour": "60 minutes",
      "answerFive": "0 minutes",
      "answerSix": "15 minutes",
      "answerSeven": "10 minutes",
      "answerOnePts": 30,
      "answerTwoPts": 23,
      "answerThreePts": 16,
      "answerFourPts": 12,
      "answerFivePts": 6,
      "answerSixPts": 5,
      "answerSevenPts": 4,
      "numberOfQuestions": 7
  }
]